### PR TITLE
Retrieve bitstring for basic_bloom_filter

### PR DESCRIPTION
**Pull request by mborger**
I created a method for retrieving the bitstring representation of a basic_bloom_filter. This is useful for storing the state of a Bloom filter.

### CODE REVIEW

**Comment by mavam** [comment]
Thanks for your pull request.

I can see your idea: you want an ASCII representation of the bitstream. For serialization?! But rather than using a member function for this, I'd prefer if you added a free function `to_string` and create an overload for the respective Bloom filters. Because the concept of "stringification" is orthogonal to the main functionality provided by Bloom filter classes, it clutters the API. What you want is that the Bloom filters model a `Printable` concept. We don't have crisp concepts in C++11 yet, but this is certainly an application for [concepts-based polymorphism](https://parasol.tamu.edu/people/bs/622-GP/value-semantics.pdf).

Would you mind changing your patch accordingly?

**Comment by mborger** [comment]
My desire for this is to store the state of the bloom filter's bit vector in a database for filtering. My use case only makes sense for the basic bloom filter. I see your point with the free function but perhaps the `to_string` function should operate on your `bitvector` class instead of the bloom filter class. Then we would need a way to expose the underlying `bitvector` from the `bloom_filter`. What about adding a method to `basic_bloom_filter` that returns a constant reference to the underlying `bitvector`?

**Comment by mavam** [comment]
I like your idea about the Bloom filter returning a const-reference to the underlying storage implementation. Let's call this function `storage` and let the return value be implementation-defined for each Bloom filter.  This would then be a generic way to access the underlying bit storage, which may not always be a single bit vector for other Bloom filters. For the basic Bloom filter, it would be:

    bitvector const& storage() const;

Then we can also post-pone adapting `to_string` for all Bloom filter variants.

**Comment by mborger** [comment]
I apologize for the long delay. I opened a new [pull request](https://github.com/mavam/libbf/pull/11) with the storage method discussed above.

**Pull request closed without merging**
