### PR TITLE
make static lib and position independent code

### PR DESCRIPTION
**Pull request by ekg**
This adds an additional target for libbf_static and makes the libraries build as fPIC.

### CODE REVIEW

**Comment by ekg** [comment]
Thanks for the really clean library with a great API!

I had a minor question. With the specification for the default `bf::basic_bloom_filter`, what is the meaning of the first and second parameter?

For instance, what precisely does this mean?

```
bf::basic_bloom_filter seen_pairs(0.9, 1000);
```

**Comment by mavam** [comment]
The first parameter is the desired false positive rate. The second is the capacity , i.e., the maximum number of unique values supported such that the false positive rate can be guaranteed. Another way to say this: it's the cardinality of the set your are trying to represent.

**Comment by ekg** [comment]
So 0.9 would mean that I want 90% of random queries to yield false positives when I've inserted 1000 elements into the set?

**Comment by mavam** [comment]
Kinda. It means that you will get a guaranteed FP rate of 90% if you have at most 1000 unique items inserted. Once you exceed 1000, the filter can no longer guarantee that FP rate.

**Comment by ekg** [comment]
So in practical use, I might want to set the FP rate lower, say 0.01?

**Comment by mavam** [comment]
Correct, 0.01 or lower seems reasonable for most use cases.

**Pull request merged**
